//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string BUTTON_ACCEPT {
            get {
                return ResourceManager.GetString("BUTTON_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string BUTTON_ADD {
            get {
                return ResourceManager.GetString("BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BUTTON_BACK {
            get {
                return ResourceManager.GetString("BUTTON_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string BUTTON_CHANGE {
            get {
                return ResourceManager.GetString("BUTTON_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string BUTTON_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string BUTTON_CLEAR {
            get {
                return ResourceManager.GetString("BUTTON_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string BUTTON_CLOSE {
            get {
                return ResourceManager.GetString("BUTTON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string BUTTON_CONTINUE {
            get {
                return ResourceManager.GetString("BUTTON_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string BUTTON_LOAD {
            get {
                return ResourceManager.GetString("BUTTON_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string BUTTON_LOGIN {
            get {
                return ResourceManager.GetString("BUTTON_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string BUTTON_NO {
            get {
                return ResourceManager.GetString("BUTTON_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new user.
        /// </summary>
        internal static string BUTTON_REGISTER_NEW_USER {
            get {
                return ResourceManager.GetString("BUTTON_REGISTER_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name is required..
        /// </summary>
        internal static string ERROR_ADD_COMPANY {
            get {
                return ResourceManager.GetString("ERROR_ADD_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work group name is required..
        /// </summary>
        internal static string ERROR_ADD_WORKGROUP {
            get {
                return ResourceManager.GetString("ERROR_ADD_WORKGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password is required..
        /// </summary>
        internal static string ERROR_CHANGE_PASSWPORD_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_CHANGE_PASSWPORD_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password field is required..
        /// </summary>
        internal static string ERROR_CHANGE_PASSWPORD_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_CHANGE_PASSWPORD_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        internal static string ERROR_CHANGE_PASSWPORD_MATCH_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_CHANGE_PASSWPORD_MATCH_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password is required..
        /// </summary>
        internal static string ERROR_CHANGE_PASSWPORD_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_CHANGE_PASSWPORD_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string ERROR_FIELD_GENERIC {
            get {
                return ResourceManager.GetString("ERROR_FIELD_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please change the selected file to a spreadsheet..
        /// </summary>
        internal static string ERROR_SPREADSHEET {
            get {
                return ResourceManager.GetString("ERROR_SPREADSHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file..
        /// </summary>
        internal static string ERROR_SPREADSHEET_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_SPREADSHEET_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account required additional permissions.
        /// </summary>
        internal static string LABEL_403_MESSAGE_1 {
            get {
                return ResourceManager.GetString("LABEL_403_MESSAGE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any concern please contact.
        /// </summary>
        internal static string LABEL_403_MESSAGE_2 {
            get {
                return ResourceManager.GetString("LABEL_403_MESSAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string LABEL_403_TITLE {
            get {
                return ResourceManager.GetString("LABEL_403_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        internal static string LABEL_500_MESSAGE_1 {
            get {
                return ResourceManager.GetString("LABEL_500_MESSAGE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the issue persist, notify to.
        /// </summary>
        internal static string LABEL_500_MESSAGE_2 {
            get {
                return ResourceManager.GetString("LABEL_500_MESSAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong.
        /// </summary>
        internal static string LABEL_500_TITLE {
            get {
                return ResourceManager.GetString("LABEL_500_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string LABEL_ACCOUNT {
            get {
                return ResourceManager.GetString("LABEL_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s important to change your account password at least one time per mount, in order to keep your information secure..
        /// </summary>
        internal static string LABEL_ACCOUNT_RECOMENDATION {
            get {
                return ResourceManager.GetString("LABEL_ACCOUNT_RECOMENDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        internal static string LABEL_ACCOUNT_SETTINGS {
            get {
                return ResourceManager.GetString("LABEL_ACCOUNT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set account parameters.
        /// </summary>
        internal static string LABEL_ACCOUNT_SETTINGS_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_ACCOUNT_SETTINGS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string LABEL_ACTION {
            get {
                return ResourceManager.GetString("LABEL_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string LABEL_ADD {
            get {
                return ResourceManager.GetString("LABEL_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new company.
        /// </summary>
        internal static string LABEL_ADD_NEW_COMPANY {
            get {
                return ResourceManager.GetString("LABEL_ADD_NEW_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new profile.
        /// </summary>
        internal static string LABEL_ADD_NEW_DDL_PROFILE {
            get {
                return ResourceManager.GetString("LABEL_ADD_NEW_DDL_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new module.
        /// </summary>
        internal static string LABEL_ADD_NEW_MODULE {
            get {
                return ResourceManager.GetString("LABEL_ADD_NEW_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new record.
        /// </summary>
        internal static string LABEL_ADD_NEW_RECORD {
            get {
                return ResourceManager.GetString("LABEL_ADD_NEW_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        internal static string LABEL_ADD_NEW_USER {
            get {
                return ResourceManager.GetString("LABEL_ADD_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new work group.
        /// </summary>
        internal static string LABEL_ADD_NEW_WORKGROUP {
            get {
                return ResourceManager.GetString("LABEL_ADD_NEW_WORKGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        internal static string LABEL_ADD_USER {
            get {
                return ResourceManager.GetString("LABEL_ADD_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Back to previous page.
        /// </summary>
        internal static string LABEL_BACK_PREVIUS_PAGE {
            get {
                return ResourceManager.GetString("LABEL_BACK_PREVIUS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string LABEL_CHANGE {
            get {
                return ResourceManager.GetString("LABEL_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        internal static string LABEL_CHANGES {
            get {
                return ResourceManager.GetString("LABEL_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string LABEL_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Example.
        /// </summary>
        internal static string LABEL_CHART_EXAMPLE {
            get {
                return ResourceManager.GetString("LABEL_CHART_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History.
        /// </summary>
        internal static string LABEL_CLEAR_HISTORY {
            get {
                return ResourceManager.GetString("LABEL_CLEAR_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Companies.
        /// </summary>
        internal static string LABEL_COMANY_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_COMANY_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        internal static string LABEL_COMPANIES {
            get {
                return ResourceManager.GetString("LABEL_COMPANIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance of companies.
        /// </summary>
        internal static string LABEL_COMPANIES_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_COMPANIES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change specifications of the company.
        /// </summary>
        internal static string LABEL_COMPANIES_EDIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_COMPANIES_EDIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies Report.
        /// </summary>
        internal static string LABEL_COMPANIES_REPORT {
            get {
                return ResourceManager.GetString("LABEL_COMPANIES_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of registered companies on the system.
        /// </summary>
        internal static string LABEL_COMPANIES_REPORT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_COMPANIES_REPORT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string LABEL_COMPANY {
            get {
                return ResourceManager.GetString("LABEL_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system support muliple companies, click to change the current company..
        /// </summary>
        internal static string LABEL_COMPANY_DASHBOAR_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_COMPANY_DASHBOAR_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Edit.
        /// </summary>
        internal static string LABEL_COMPANY_EDIT {
            get {
                return ResourceManager.GetString("LABEL_COMPANY_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify company details.
        /// </summary>
        internal static string LABEL_COMPANY_EDIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_COMPANY_EDIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change company.
        /// </summary>
        internal static string LABEL_COMPANY_MODAL_TITLE {
            get {
                return ResourceManager.GetString("LABEL_COMPANY_MODAL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        internal static string LABEL_COMPANY_NAME {
            get {
                return ResourceManager.GetString("LABEL_COMPANY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string LABEL_CONFIGURATION {
            get {
                return ResourceManager.GetString("LABEL_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System configuration.
        /// </summary>
        internal static string LABEL_CONFIGURATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_CONFIGURATION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string LABEL_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string LABEL_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string LABEL_DASHBOARD {
            get {
                return ResourceManager.GetString("LABEL_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview, stats, chat and more.
        /// </summary>
        internal static string LABEL_DASHBOARD_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DASHBOARD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Bases.
        /// </summary>
        internal static string LABEL_DATABASES {
            get {
                return ResourceManager.GetString("LABEL_DATABASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LABEL_DATABASES_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATABASES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default database.
        /// </summary>
        internal static string LABEL_DATABASE_DEFAULT {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LABEL_DATABASE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Details.
        /// </summary>
        internal static string LABEL_DATABASE_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string LABEL_DATABASE_NAME {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LABEL_DATABASE_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string LABEL_DATABASE_SERVER {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string LABEL_DATABASE_USER {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Load.
        /// </summary>
        internal static string LABEL_
        
        {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic data load.
        /// </summary>
        internal static string LABEL_DATALOAD_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string LABEL_DATALOAD_HISTORY {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical of previous data loads.
        /// </summary>
        internal static string LABEL_DATALOAD_HISTORY_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_HISTORY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module is intended for load data dynamically, using as source  spreadsheets files..
        /// </summary>
        internal static string LABEL_DATALOAD_LONG_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_LONG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string LABEL_DATALOAD_PROFILES {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of profiles for dynamic data load.
        /// </summary>
        internal static string LABEL_DATALOAD_PROFILES_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_PROFILES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of load profiles.
        /// </summary>
        internal static string LABEL_DATALOAD_PROFILE_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_PROFILE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change specifications of the data load profile.
        /// </summary>
        internal static string LABEL_DATALOAD_PROFILE_EDIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_PROFILE_EDIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string LABEL_DATALOAD_SUMMARY {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summarize the results of the data load process.
        /// </summary>
        internal static string LABEL_DATALOAD_SUMMARY_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_SUMMARY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LABEL_DATE_GRID {
            get {
                return ResourceManager.GetString("LABEL_DATE_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string LABEL_DELETE {
            get {
                return ResourceManager.GetString("LABEL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted records: .
        /// </summary>
        internal static string LABEL_DELETED_RECORDS {
            get {
                return ResourceManager.GetString("LABEL_DELETED_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string LABEL_DELETES_GRID {
            get {
                return ResourceManager.GetString("LABEL_DELETES_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current data.
        /// </summary>
        internal static string LABEL_DELETE_CURRENT_DATA {
            get {
                return ResourceManager.GetString("LABEL_DELETE_CURRENT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string LABEL_DETAIL {
            get {
                return ResourceManager.GetString("LABEL_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string LABEL_DURATION {
            get {
                return ResourceManager.GetString("LABEL_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string LABEL_EDIT {
            get {
                return ResourceManager.GetString("LABEL_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies Edit.
        /// </summary>
        internal static string LABEL_EDIT_COMPANIES {
            get {
                return ResourceManager.GetString("LABEL_EDIT_COMPANIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Edit.
        /// </summary>
        internal static string LABEL_EDIT_FROFILE {
            get {
                return ResourceManager.GetString("LABEL_EDIT_FROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English [ENG].
        /// </summary>
        internal static string LABEL_ENGLISH {
            get {
                return ResourceManager.GetString("LABEL_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors: .
        /// </summary>
        internal static string LABEL_ERRORS {
            get {
                return ResourceManager.GetString("LABEL_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string LABEL_ERRORS_GRID {
            get {
                return ResourceManager.GetString("LABEL_ERRORS_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External ID.
        /// </summary>
        internal static string LABEL_EXTERNAL_ID {
            get {
                return ResourceManager.GetString("LABEL_EXTERNAL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string LABEL_FILE {
            get {
                return ResourceManager.GetString("LABEL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string LABEL_FILENAME_GRID {
            get {
                return ResourceManager.GetString("LABEL_FILENAME_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Description.
        /// </summary>
        internal static string LABEL_FILE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_FILE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Navbar.
        /// </summary>
        internal static string LABEL_FIXED_NAVBAR {
            get {
                return ResourceManager.GetString("LABEL_FIXED_NAVBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Sidebar.
        /// </summary>
        internal static string LABEL_FIXED_SIDEBAR {
            get {
                return ResourceManager.GetString("LABEL_FIXED_SIDEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO.
        /// </summary>
        internal static string LABEL_GO {
            get {
                return ResourceManager.GetString("LABEL_GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to dashboard.
        /// </summary>
        internal static string LABEL_GO_TO_DASHOARD {
            get {
                return ResourceManager.GetString("LABEL_GO_TO_DASHOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string LABEL_HISTORY {
            get {
                return ResourceManager.GetString("LABEL_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: This action can not be reversed. Are you sure you want to delete the history?.
        /// </summary>
        internal static string LABEL_HISTORY_CLEAR_MESSAGE {
            get {
                return ResourceManager.GetString("LABEL_HISTORY_CLEAR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are required to be a minimum of 6 characters in length..
        /// </summary>
        internal static string LABEL_INFO_NEW_USER {
            get {
                return ResourceManager.GetString("LABEL_INFO_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string LABEL_INSERTS_GRID {
            get {
                return ResourceManager.GetString("LABEL_INSERTS_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules list.
        /// </summary>
        internal static string LABEL_LIST_MODULES {
            get {
                return ResourceManager.GetString("LABEL_LIST_MODULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded file:.
        /// </summary>
        internal static string LABEL_LOADED_FILE {
            get {
                return ResourceManager.GetString("LABEL_LOADED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads.
        /// </summary>
        internal static string LABEL_LOADS {
            get {
                return ResourceManager.GetString("LABEL_LOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LABEL_LOGOUT {
            get {
                return ResourceManager.GetString("LABEL_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string LABEL_MODULE {
            get {
                return ResourceManager.GetString("LABEL_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string LABEL_MODULES {
            get {
                return ResourceManager.GetString("LABEL_MODULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System modules.
        /// </summary>
        internal static string LABEL_MODULES_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_MODULES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System modules.
        /// </summary>
        internal static string LABEL_MODULE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_MODULE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Modules.
        /// </summary>
        internal static string LABEL_MODULE_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_MODULE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Edit.
        /// </summary>
        internal static string LABEL_MODULE_EDIT {
            get {
                return ResourceManager.GetString("LABEL_MODULE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        internal static string LABEL_MODULE_NAME {
            get {
                return ResourceManager.GetString("LABEL_MODULE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string LABEL_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New records: .
        /// </summary>
        internal static string LABEL_NEW_RECORDS {
            get {
                return ResourceManager.GetString("LABEL_NEW_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE!.
        /// </summary>
        internal static string LABEL_NOTE {
            get {
                return ResourceManager.GetString("LABEL_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process requires a spreadsheet only..
        /// </summary>
        internal static string LABEL_NOTE_MESSAGE {
            get {
                return ResourceManager.GetString("LABEL_NOTE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options list.
        /// </summary>
        internal static string LABEL_OPTIONS_LIST {
            get {
                return ResourceManager.GetString("LABEL_OPTIONS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LABEL_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset.
        /// </summary>
        internal static string LABEL_PASSWORD_RESET {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string LABEL_PEOPLE {
            get {
                return ResourceManager.GetString("LABEL_PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People from Costa Rica&apos;s sensus, module with demonstrative purposes.
        /// </summary>
        internal static string LABEL_PEOPLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_PEOPLE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People List.
        /// </summary>
        internal static string LABEL_PEOPLE_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_PEOPLE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string LABEL_PERMISSIONS {
            get {
                return ResourceManager.GetString("LABEL_PERMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LABEL_PERMISSIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_PERMISSIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string LABEL_PERSON_ID {
            get {
                return ResourceManager.GetString("LABEL_PERSON_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LABEL_PERSON_LASTNAME {
            get {
                return ResourceManager.GetString("LABEL_PERSON_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LABEL_PERSON_NAME {
            get {
                return ResourceManager.GetString("LABEL_PERSON_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure.
        /// </summary>
        internal static string LABEL_PROCEDURE {
            get {
                return ResourceManager.GetString("LABEL_PROCEDURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string LABEL_PROFILE {
            get {
                return ResourceManager.GetString("LABEL_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string LABEL_PROFILES {
            get {
                return ResourceManager.GetString("LABEL_PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Description.
        /// </summary>
        internal static string LABEL_PROFILE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_PROFILE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Name.
        /// </summary>
        internal static string LABEL_PROFILE_NAME {
            get {
                return ResourceManager.GetString("LABEL_PROFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedure.
        /// </summary>
        internal static string LABEL_PROFILE_STOREPROCEDURE {
            get {
                return ResourceManager.GetString("LABEL_PROFILE_STOREPROCEDURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string LABEL_REFRESH {
            get {
                return ResourceManager.GetString("LABEL_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        internal static string LABEL_REMEMBER {
            get {
                return ResourceManager.GetString("LABEL_REMEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string LABEL_REMOVE {
            get {
                return ResourceManager.GetString("LABEL_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string LABEL_REPORT {
            get {
                return ResourceManager.GetString("LABEL_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string LABEL_ROLES {
            get {
                return ResourceManager.GetString("LABEL_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search . . ..
        /// </summary>
        internal static string LABEL_SEARCH {
            get {
                return ResourceManager.GetString("LABEL_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        internal static string LABEL_SELECT_FILE {
            get {
                return ResourceManager.GetString("LABEL_SELECT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string LABEL_SETTINGS {
            get {
                return ResourceManager.GetString("LABEL_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet name.
        /// </summary>
        internal static string LABEL_SHEET_NAME {
            get {
                return ResourceManager.GetString("LABEL_SHEET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish [ESP].
        /// </summary>
        internal static string LABEL_SPANISH {
            get {
                return ResourceManager.GetString("LABEL_SPANISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreadsheet.
        /// </summary>
        internal static string LABEL_SPREADSHEET {
            get {
                return ResourceManager.GetString("LABEL_SPREADSHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedure Example.
        /// </summary>
        internal static string LABEL_SP_EXAMPLE {
            get {
                return ResourceManager.GetString("LABEL_SP_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP Example.
        /// </summary>
        internal static string LABEL_STOREPROCEDURE_EXAMPLE {
            get {
                return ResourceManager.GetString("LABEL_STOREPROCEDURE_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated records: .
        /// </summary>
        internal static string LABEL_UPDATED_RECORDS {
            get {
                return ResourceManager.GetString("LABEL_UPDATED_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string LABEL_UPDATES_GRID {
            get {
                return ResourceManager.GetString("LABEL_UPDATES_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LABEL_USER {
            get {
                return ResourceManager.GetString("LABEL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string LABEL_USERS {
            get {
                return ResourceManager.GetString("LABEL_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance of users.
        /// </summary>
        internal static string LABEL_USERS_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_USERS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        internal static string LABEL_USER_ADD_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_USER_ADD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance of users.
        /// </summary>
        internal static string LABEL_USER_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_USER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Users.
        /// </summary>
        internal static string LABEL_USER_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_USER_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Edit.
        /// </summary>
        internal static string LABEL_USER_EDIT {
            get {
                return ResourceManager.GetString("LABEL_USER_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user details.
        /// </summary>
        internal static string LABEL_USER_EDIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_USER_EDIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        internal static string LABEL_USER_INFORMATION {
            get {
                return ResourceManager.GetString("LABEL_USER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string LABEL_VIEW {
            get {
                return ResourceManager.GetString("LABEL_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        internal static string LABEL_WIZARD {
            get {
                return ResourceManager.GetString("LABEL_WIZARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Groups.
        /// </summary>
        internal static string LABEL_WORKGROUPS {
            get {
                return ResourceManager.GetString("LABEL_WORKGROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance of work groups.
        /// </summary>
        internal static string LABEL_WORKGROUPS_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_WORKGROUPS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of work groups.
        /// </summary>
        internal static string LABEL_WORKGROUP_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_WORKGROUP_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Group Edit.
        /// </summary>
        internal static string LABEL_WORKGROUP_EDIT {
            get {
                return ResourceManager.GetString("LABEL_WORKGROUP_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify work group details.
        /// </summary>
        internal static string LABEL_WORKGROUP_EDIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_WORKGROUP_EDIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Group Name.
        /// </summary>
        internal static string LABEL_WORKGROUP_NAME {
            get {
                return ResourceManager.GetString("LABEL_WORKGROUP_NAME", resourceCulture);
            }
        }
    }
}
