//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string BUTTON_ACCEPT {
            get {
                return ResourceManager.GetString("BUTTON_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string BUTTON_ADD {
            get {
                return ResourceManager.GetString("BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string BUTTON_BACK {
            get {
                return ResourceManager.GetString("BUTTON_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change.
        /// </summary>
        internal static string BUTTON_CHANGE {
            get {
                return ResourceManager.GetString("BUTTON_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        internal static string BUTTON_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        internal static string BUTTON_CLEAR {
            get {
                return ResourceManager.GetString("BUTTON_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string BUTTON_CLOSE {
            get {
                return ResourceManager.GetString("BUTTON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        internal static string BUTTON_CONTINUE {
            get {
                return ResourceManager.GetString("BUTTON_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load.
        /// </summary>
        internal static string BUTTON_LOAD {
            get {
                return ResourceManager.GetString("BUTTON_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        internal static string BUTTON_LOGIN {
            get {
                return ResourceManager.GetString("BUTTON_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string BUTTON_NO {
            get {
                return ResourceManager.GetString("BUTTON_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register new user.
        /// </summary>
        internal static string BUTTON_REGISTER_NEW_USER {
            get {
                return ResourceManager.GetString("BUTTON_REGISTER_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company name is required..
        /// </summary>
        internal static string ERROR_ADD_COMPANY {
            get {
                return ResourceManager.GetString("ERROR_ADD_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work group name is required..
        /// </summary>
        internal static string ERROR_ADD_WORKGROUP {
            get {
                return ResourceManager.GetString("ERROR_ADD_WORKGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm new password is required..
        /// </summary>
        internal static string ERROR_CHANGE_PASSWPORD_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_CHANGE_PASSWPORD_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current password field is required..
        /// </summary>
        internal static string ERROR_CHANGE_PASSWPORD_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_CHANGE_PASSWPORD_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new password and confirmation password do not match..
        /// </summary>
        internal static string ERROR_CHANGE_PASSWPORD_MATCH_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_CHANGE_PASSWPORD_MATCH_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new password is required..
        /// </summary>
        internal static string ERROR_CHANGE_PASSWPORD_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_CHANGE_PASSWPORD_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *.
        /// </summary>
        internal static string ERROR_FIELD_GENERIC {
            get {
                return ResourceManager.GetString("ERROR_FIELD_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please change the selected file to a spreadsheet..
        /// </summary>
        internal static string ERROR_SPREADSHEET {
            get {
                return ResourceManager.GetString("ERROR_SPREADSHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a file..
        /// </summary>
        internal static string ERROR_SPREADSHEET_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_SPREADSHEET_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo expirado por no uso del sistema.
        /// </summary>
        internal static string LABEL_403_MESSAGE_1 {
            get {
                return ResourceManager.GetString("LABEL_403_MESSAGE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you have any concern please contact.
        /// </summary>
        internal static string LABEL_403_MESSAGE_2 {
            get {
                return ResourceManager.GetString("LABEL_403_MESSAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sessión Expirada.
        /// </summary>
        internal static string LABEL_403_TITLE {
            get {
                return ResourceManager.GetString("LABEL_403_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please try again.
        /// </summary>
        internal static string LABEL_500_MESSAGE_1 {
            get {
                return ResourceManager.GetString("LABEL_500_MESSAGE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If the issue persist, notify to.
        /// </summary>
        internal static string LABEL_500_MESSAGE_2 {
            get {
                return ResourceManager.GetString("LABEL_500_MESSAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Something Went Wrong.
        /// </summary>
        internal static string LABEL_500_TITLE {
            get {
                return ResourceManager.GetString("LABEL_500_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account.
        /// </summary>
        internal static string LABEL_ACCOUNT {
            get {
                return ResourceManager.GetString("LABEL_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It&apos;s important to change your account password at least one time per mount, in order to keep your information secure..
        /// </summary>
        internal static string LABEL_ACCOUNT_RECOMENDATION {
            get {
                return ResourceManager.GetString("LABEL_ACCOUNT_RECOMENDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Settings.
        /// </summary>
        internal static string LABEL_ACCOUNT_SETTINGS {
            get {
                return ResourceManager.GetString("LABEL_ACCOUNT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set account parameters.
        /// </summary>
        internal static string LABEL_ACCOUNT_SETTINGS_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_ACCOUNT_SETTINGS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action.
        /// </summary>
        internal static string LABEL_ACTION {
            get {
                return ResourceManager.GetString("LABEL_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string LABEL_ADD {
            get {
                return ResourceManager.GetString("LABEL_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new company.
        /// </summary>
        internal static string LABEL_ADD_NEW_COMPANY {
            get {
                return ResourceManager.GetString("LABEL_ADD_NEW_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new profile.
        /// </summary>
        internal static string LABEL_ADD_NEW_DDL_PROFILE {
            get {
                return ResourceManager.GetString("LABEL_ADD_NEW_DDL_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new module.
        /// </summary>
        internal static string LABEL_ADD_NEW_MODULE {
            get {
                return ResourceManager.GetString("LABEL_ADD_NEW_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new record.
        /// </summary>
        internal static string LABEL_ADD_NEW_RECORD {
            get {
                return ResourceManager.GetString("LABEL_ADD_NEW_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new user.
        /// </summary>
        internal static string LABEL_ADD_NEW_USER {
            get {
                return ResourceManager.GetString("LABEL_ADD_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new work group.
        /// </summary>
        internal static string LABEL_ADD_NEW_WORKGROUP {
            get {
                return ResourceManager.GetString("LABEL_ADD_NEW_WORKGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add user.
        /// </summary>
        internal static string LABEL_ADD_USER {
            get {
                return ResourceManager.GetString("LABEL_ADD_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ← Back to previous page.
        /// </summary>
        internal static string LABEL_BACK_PREVIUS_PAGE {
            get {
                return ResourceManager.GetString("LABEL_BACK_PREVIUS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change.
        /// </summary>
        internal static string LABEL_CHANGE {
            get {
                return ResourceManager.GetString("LABEL_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changes.
        /// </summary>
        internal static string LABEL_CHANGES {
            get {
                return ResourceManager.GetString("LABEL_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        internal static string LABEL_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chart Example.
        /// </summary>
        internal static string LABEL_CHART_EXAMPLE {
            get {
                return ResourceManager.GetString("LABEL_CHART_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear History.
        /// </summary>
        internal static string LABEL_CLEAR_HISTORY {
            get {
                return ResourceManager.GetString("LABEL_CLEAR_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of Companies.
        /// </summary>
        internal static string LABEL_COMANY_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_COMANY_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Companies.
        /// </summary>
        internal static string LABEL_COMPANIES {
            get {
                return ResourceManager.GetString("LABEL_COMPANIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maintenance of companies.
        /// </summary>
        internal static string LABEL_COMPANIES_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_COMPANIES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change specifications of the company.
        /// </summary>
        internal static string LABEL_COMPANIES_EDIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_COMPANIES_EDIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Companies Report.
        /// </summary>
        internal static string LABEL_COMPANIES_REPORT {
            get {
                return ResourceManager.GetString("LABEL_COMPANIES_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of registered companies on the system.
        /// </summary>
        internal static string LABEL_COMPANIES_REPORT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_COMPANIES_REPORT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company.
        /// </summary>
        internal static string LABEL_COMPANY {
            get {
                return ResourceManager.GetString("LABEL_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The system support muliple companies, click to change the current company..
        /// </summary>
        internal static string LABEL_COMPANY_DASHBOAR_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_COMPANY_DASHBOAR_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company Edit.
        /// </summary>
        internal static string LABEL_COMPANY_EDIT {
            get {
                return ResourceManager.GetString("LABEL_COMPANY_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify company details.
        /// </summary>
        internal static string LABEL_COMPANY_EDIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_COMPANY_EDIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change company.
        /// </summary>
        internal static string LABEL_COMPANY_MODAL_TITLE {
            get {
                return ResourceManager.GetString("LABEL_COMPANY_MODAL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company name.
        /// </summary>
        internal static string LABEL_COMPANY_NAME {
            get {
                return ResourceManager.GetString("LABEL_COMPANY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        internal static string LABEL_CONFIGURATION {
            get {
                return ResourceManager.GetString("LABEL_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System configuration.
        /// </summary>
        internal static string LABEL_CONFIGURATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_CONFIGURATION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm new password.
        /// </summary>
        internal static string LABEL_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password.
        /// </summary>
        internal static string LABEL_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard.
        /// </summary>
        internal static string LABEL_DASHBOARD {
            get {
                return ResourceManager.GetString("LABEL_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overview, stats, chat and more.
        /// </summary>
        internal static string LABEL_DASHBOARD_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DASHBOARD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Bases.
        /// </summary>
        internal static string LABEL_DATABASES {
            get {
                return ResourceManager.GetString("LABEL_DATABASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string LABEL_DATABASES_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATABASES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default database.
        /// </summary>
        internal static string LABEL_DATABASE_DEFAULT {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string LABEL_DATABASE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database Details.
        /// </summary>
        internal static string LABEL_DATABASE_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database.
        /// </summary>
        internal static string LABEL_DATABASE_NAME {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string LABEL_DATABASE_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server.
        /// </summary>
        internal static string LABEL_DATABASE_SERVER {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string LABEL_DATABASE_USER {
            get {
                return ResourceManager.GetString("LABEL_DATABASE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Load.
        /// </summary>
        internal static string LABEL_DATALOAD {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dynamic data load.
        /// </summary>
        internal static string LABEL_DATALOAD_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History.
        /// </summary>
        internal static string LABEL_DATALOAD_HISTORY {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historical of previous data loads.
        /// </summary>
        internal static string LABEL_DATALOAD_HISTORY_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_HISTORY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This module is intended for load data dynamically, using as source  spreadsheets files..
        /// </summary>
        internal static string LABEL_DATALOAD_LONG_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_LONG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profiles.
        /// </summary>
        internal static string LABEL_DATALOAD_PROFILES {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of profiles for dynamic data load.
        /// </summary>
        internal static string LABEL_DATALOAD_PROFILES_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_PROFILES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of load profiles.
        /// </summary>
        internal static string LABEL_DATALOAD_PROFILE_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_PROFILE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change specifications of the data load profile.
        /// </summary>
        internal static string LABEL_DATALOAD_PROFILE_EDIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_PROFILE_EDIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Summary.
        /// </summary>
        internal static string LABEL_DATALOAD_SUMMARY {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Summarize the results of the data load process.
        /// </summary>
        internal static string LABEL_DATALOAD_SUMMARY_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DATALOAD_SUMMARY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string LABEL_DATE_GRID {
            get {
                return ResourceManager.GetString("LABEL_DATE_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string LABEL_DELETE {
            get {
                return ResourceManager.GetString("LABEL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleted records: .
        /// </summary>
        internal static string LABEL_DELETED_RECORDS {
            get {
                return ResourceManager.GetString("LABEL_DELETED_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleted.
        /// </summary>
        internal static string LABEL_DELETES_GRID {
            get {
                return ResourceManager.GetString("LABEL_DELETES_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete current data.
        /// </summary>
        internal static string LABEL_DELETE_CURRENT_DATA {
            get {
                return ResourceManager.GetString("LABEL_DELETE_CURRENT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detail.
        /// </summary>
        internal static string LABEL_DETAIL {
            get {
                return ResourceManager.GetString("LABEL_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duration.
        /// </summary>
        internal static string LABEL_DURATION {
            get {
                return ResourceManager.GetString("LABEL_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string LABEL_EDIT {
            get {
                return ResourceManager.GetString("LABEL_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Companies Edit.
        /// </summary>
        internal static string LABEL_EDIT_COMPANIES {
            get {
                return ResourceManager.GetString("LABEL_EDIT_COMPANIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile Edit.
        /// </summary>
        internal static string LABEL_EDIT_FROFILE {
            get {
                return ResourceManager.GetString("LABEL_EDIT_FROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English [ENG].
        /// </summary>
        internal static string LABEL_ENGLISH {
            get {
                return ResourceManager.GetString("LABEL_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errors: .
        /// </summary>
        internal static string LABEL_ERRORS {
            get {
                return ResourceManager.GetString("LABEL_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errors.
        /// </summary>
        internal static string LABEL_ERRORS_GRID {
            get {
                return ResourceManager.GetString("LABEL_ERRORS_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a External ID.
        /// </summary>
        internal static string LABEL_EXTERNAL_ID {
            get {
                return ResourceManager.GetString("LABEL_EXTERNAL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File.
        /// </summary>
        internal static string LABEL_FILE {
            get {
                return ResourceManager.GetString("LABEL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File Name.
        /// </summary>
        internal static string LABEL_FILENAME_GRID {
            get {
                return ResourceManager.GetString("LABEL_FILENAME_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File Description.
        /// </summary>
        internal static string LABEL_FILE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_FILE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fixed Navbar.
        /// </summary>
        internal static string LABEL_FIXED_NAVBAR {
            get {
                return ResourceManager.GetString("LABEL_FIXED_NAVBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fixed Sidebar.
        /// </summary>
        internal static string LABEL_FIXED_SIDEBAR {
            get {
                return ResourceManager.GetString("LABEL_FIXED_SIDEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GO.
        /// </summary>
        internal static string LABEL_GO {
            get {
                return ResourceManager.GetString("LABEL_GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to dashboard.
        /// </summary>
        internal static string LABEL_GO_TO_DASHOARD {
            get {
                return ResourceManager.GetString("LABEL_GO_TO_DASHOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History.
        /// </summary>
        internal static string LABEL_HISTORY {
            get {
                return ResourceManager.GetString("LABEL_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning: This action can not be reversed. Are you sure you want to delete the history?.
        /// </summary>
        internal static string LABEL_HISTORY_CLEAR_MESSAGE {
            get {
                return ResourceManager.GetString("LABEL_HISTORY_CLEAR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords are required to be a minimum of 6 characters in length..
        /// </summary>
        internal static string LABEL_INFO_NEW_USER {
            get {
                return ResourceManager.GetString("LABEL_INFO_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        internal static string LABEL_INSERTS_GRID {
            get {
                return ResourceManager.GetString("LABEL_INSERTS_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modules list.
        /// </summary>
        internal static string LABEL_LIST_MODULES {
            get {
                return ResourceManager.GetString("LABEL_LIST_MODULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loaded file:.
        /// </summary>
        internal static string LABEL_LOADED_FILE {
            get {
                return ResourceManager.GetString("LABEL_LOADED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loads.
        /// </summary>
        internal static string LABEL_LOADS {
            get {
                return ResourceManager.GetString("LABEL_LOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        internal static string LABEL_LOGOUT {
            get {
                return ResourceManager.GetString("LABEL_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Module.
        /// </summary>
        internal static string LABEL_MODULE {
            get {
                return ResourceManager.GetString("LABEL_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modules.
        /// </summary>
        internal static string LABEL_MODULES {
            get {
                return ResourceManager.GetString("LABEL_MODULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System modules.
        /// </summary>
        internal static string LABEL_MODULES_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_MODULES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System modules.
        /// </summary>
        internal static string LABEL_MODULE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_MODULE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of Modules.
        /// </summary>
        internal static string LABEL_MODULE_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_MODULE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Module Edit.
        /// </summary>
        internal static string LABEL_MODULE_EDIT {
            get {
                return ResourceManager.GetString("LABEL_MODULE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Module Name.
        /// </summary>
        internal static string LABEL_MODULE_NAME {
            get {
                return ResourceManager.GetString("LABEL_MODULE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        internal static string LABEL_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New records: .
        /// </summary>
        internal static string LABEL_NEW_RECORDS {
            get {
                return ResourceManager.GetString("LABEL_NEW_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOTE!.
        /// </summary>
        internal static string LABEL_NOTE {
            get {
                return ResourceManager.GetString("LABEL_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The process requires a spreadsheet only..
        /// </summary>
        internal static string LABEL_NOTE_MESSAGE {
            get {
                return ResourceManager.GetString("LABEL_NOTE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options list.
        /// </summary>
        internal static string LABEL_OPTIONS_LIST {
            get {
                return ResourceManager.GetString("LABEL_OPTIONS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string LABEL_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password reset.
        /// </summary>
        internal static string LABEL_PASSWORD_RESET {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a People.
        /// </summary>
        internal static string LABEL_PEOPLE {
            get {
                return ResourceManager.GetString("LABEL_PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a People from Costa Rica&apos;s sensus, module with demonstrative purposes.
        /// </summary>
        internal static string LABEL_PEOPLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_PEOPLE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a People List.
        /// </summary>
        internal static string LABEL_PEOPLE_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_PEOPLE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permissions.
        /// </summary>
        internal static string LABEL_PERMISSIONS {
            get {
                return ResourceManager.GetString("LABEL_PERMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string LABEL_PERMISSIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_PERMISSIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string LABEL_PERSON_ID {
            get {
                return ResourceManager.GetString("LABEL_PERSON_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        internal static string LABEL_PERSON_LASTNAME {
            get {
                return ResourceManager.GetString("LABEL_PERSON_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string LABEL_PERSON_NAME {
            get {
                return ResourceManager.GetString("LABEL_PERSON_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure.
        /// </summary>
        internal static string LABEL_PROCEDURE {
            get {
                return ResourceManager.GetString("LABEL_PROCEDURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        internal static string LABEL_PROFILE {
            get {
                return ResourceManager.GetString("LABEL_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profiles.
        /// </summary>
        internal static string LABEL_PROFILES {
            get {
                return ResourceManager.GetString("LABEL_PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile Description.
        /// </summary>
        internal static string LABEL_PROFILE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_PROFILE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile Name.
        /// </summary>
        internal static string LABEL_PROFILE_NAME {
            get {
                return ResourceManager.GetString("LABEL_PROFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stored Procedure.
        /// </summary>
        internal static string LABEL_PROFILE_STOREPROCEDURE {
            get {
                return ResourceManager.GetString("LABEL_PROFILE_STOREPROCEDURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh.
        /// </summary>
        internal static string LABEL_REFRESH {
            get {
                return ResourceManager.GetString("LABEL_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember me?.
        /// </summary>
        internal static string LABEL_REMEMBER {
            get {
                return ResourceManager.GetString("LABEL_REMEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        internal static string LABEL_REMOVE {
            get {
                return ResourceManager.GetString("LABEL_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        internal static string LABEL_REPORT {
            get {
                return ResourceManager.GetString("LABEL_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roles.
        /// </summary>
        internal static string LABEL_ROLES {
            get {
                return ResourceManager.GetString("LABEL_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search . . ..
        /// </summary>
        internal static string LABEL_SEARCH {
            get {
                return ResourceManager.GetString("LABEL_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select file.
        /// </summary>
        internal static string LABEL_SELECT_FILE {
            get {
                return ResourceManager.GetString("LABEL_SELECT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string LABEL_SETTINGS {
            get {
                return ResourceManager.GetString("LABEL_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sheet name.
        /// </summary>
        internal static string LABEL_SHEET_NAME {
            get {
                return ResourceManager.GetString("LABEL_SHEET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish [ESP].
        /// </summary>
        internal static string LABEL_SPANISH {
            get {
                return ResourceManager.GetString("LABEL_SPANISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spreadsheet.
        /// </summary>
        internal static string LABEL_SPREADSHEET {
            get {
                return ResourceManager.GetString("LABEL_SPREADSHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stored Procedure Example.
        /// </summary>
        internal static string LABEL_SP_EXAMPLE {
            get {
                return ResourceManager.GetString("LABEL_SP_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SP Example.
        /// </summary>
        internal static string LABEL_STOREPROCEDURE_EXAMPLE {
            get {
                return ResourceManager.GetString("LABEL_STOREPROCEDURE_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updated records: .
        /// </summary>
        internal static string LABEL_UPDATED_RECORDS {
            get {
                return ResourceManager.GetString("LABEL_UPDATED_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updated.
        /// </summary>
        internal static string LABEL_UPDATES_GRID {
            get {
                return ResourceManager.GetString("LABEL_UPDATES_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string LABEL_USER {
            get {
                return ResourceManager.GetString("LABEL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        internal static string LABEL_USERS {
            get {
                return ResourceManager.GetString("LABEL_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maintenance of users.
        /// </summary>
        internal static string LABEL_USERS_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_USERS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new user.
        /// </summary>
        internal static string LABEL_USER_ADD_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_USER_ADD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maintenance of users.
        /// </summary>
        internal static string LABEL_USER_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_USER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of Users.
        /// </summary>
        internal static string LABEL_USER_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_USER_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Edit.
        /// </summary>
        internal static string LABEL_USER_EDIT {
            get {
                return ResourceManager.GetString("LABEL_USER_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify user details.
        /// </summary>
        internal static string LABEL_USER_EDIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_USER_EDIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Information.
        /// </summary>
        internal static string LABEL_USER_INFORMATION {
            get {
                return ResourceManager.GetString("LABEL_USER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View.
        /// </summary>
        internal static string LABEL_VIEW {
            get {
                return ResourceManager.GetString("LABEL_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wizard.
        /// </summary>
        internal static string LABEL_WIZARD {
            get {
                return ResourceManager.GetString("LABEL_WIZARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work Groups.
        /// </summary>
        internal static string LABEL_WORKGROUPS {
            get {
                return ResourceManager.GetString("LABEL_WORKGROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maintenance of work groups.
        /// </summary>
        internal static string LABEL_WORKGROUPS_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_WORKGROUPS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of work groups.
        /// </summary>
        internal static string LABEL_WORKGROUP_DETAILS {
            get {
                return ResourceManager.GetString("LABEL_WORKGROUP_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work Group Edit.
        /// </summary>
        internal static string LABEL_WORKGROUP_EDIT {
            get {
                return ResourceManager.GetString("LABEL_WORKGROUP_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify work group details.
        /// </summary>
        internal static string LABEL_WORKGROUP_EDIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_WORKGROUP_EDIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work Group Name.
        /// </summary>
        internal static string LABEL_WORKGROUP_NAME {
            get {
                return ResourceManager.GetString("LABEL_WORKGROUP_NAME", resourceCulture);
            }
        }
    }
}
